var tool={$:function(a){return"object"===typeof a?a:document.getElementById(a)},$$:function(a,b){return(b||document).getElementsByTagName(a)},$$$:function(a,b,c){for(var d=0,e=[],a=RegExp("(^|\\s)"+a+"(\\s|$)"),b=tool.$$(b||"*",c||document),d=0;d<b.length;d++)a.test(b[d].className)&&e.push(b[d]);return e},addClass:function(a,b){!a.className?a.className=b:a.className+=" "+b},removeClass:function(a,b){var c=RegExp("(\\s|^)"+b+"(\\s|$)");a.className.match(c)&&(a.className=a.className.replace(c," "))},
addHandler:function(a,b,c,d){var e={a:["addEventListener","attachEvent"],r:["removeEventListener","datachEvent"]},e=!0===d?e.r:e.a;if(a[e[0]])a[e[0]](b,c,!1);else if(a.attachEvent)a[e[1]]("on"+b,c);else a["on"+b]=!0===d?c:null},removeHandler:function(a,b,c){this.addHandler(a,b,c,!0)},getPos:function(a){if(a){var b=0,c=0;if("getBoundingClientRect"in document.documentElement)var c=a.getBoundingClientRect(),b=a.ownerDocument,a=b.body,d=b.documentElement,e=b.clientTop||a.clientTop||0,b=c.left+(self.pageXOffset||
d&&d.scrollLeft||a.scrollTop)-(b.clientLeft||a.clientLeft||0),c=c.top+(self.pageYOffset||d&&d.scrollTop||a.scrollTop)-e;else{do c+=a.offsetTop,b+=a.offsetLeft,a=elel.offsetParent;while(a)}return{left:b,top:c}}},getW:function(){return o={w:document.documentElement.clientWidth||document.body.clientWidth,h:document.documentElement.clientHeight||document.body.clientHeight,s:document.documentElement.scrollTop||document.body.scrollTop}},$M:function(a,b){if(a){var c,d,e;c=a.style;for(var f in b)switch(e=
b[f],d=e+"px",f){case "t":c.top=d;break;case "d":c.display=e;break;default:c[f]=e}}},getCss:function(a){return document.defaultView&&document.defaultView.getComputedStyle?document.defaultView.getComputedStyle(a,null):a.currentStyle},extend:function(a,b){for(var c in b)a[c]=b[c];return a}};
function Focusimg(a){var b={b:null,s:null,text:null,t:3E3,cur:"cur"};tool.extend(b,a);var c=this;c.b=tool.$(b.b);c.ul=tool.$$("ul",c.b)[0];c.h=c.b.offsetHeight;c.s=tool.$(b.s);c.li=tool.$$("li",c.s);c.l=c.li.length;c.text=tool.$$$(b.text);c.t=b.t;c.c=0;c.old=0;c.timer=null;c.autoTimer=null;c.cur=b.cur;c.autoPlay();c.move();c.liTimer=null;a=0;for(b=c.li.length;a<b;a++)c.li[a].i=a,c.li[a].onmouseover=function(){var a=this;c.liTimer&&clearTimeout(c.liTimer);c.liTimer=setTimeout(function(){a.i!==c.c&&
(c.autoTimer&&clearTimeout(c.autoTimer),c.c=a.i,c.move(1))},100)}}
Focusimg.prototype={autoPlay:function(){var a=this;a.autoTimer=setTimeout(function(){a.c<a.l-1?a.c++:a.c=0;a.move();a.autoPlay()},a.t)},move:function(a){var b=this,c=Math.abs(b.c*b.h),d;b.timer&&clearInterval(b.timer);b.timer=setInterval(function(){d=Math.abs(parseInt(tool.getCss(b.ul).top));d+=Math.floor((c-d)/2);1>=Math.abs(c-d)&&(d=c,clearInterval(b.timer),a&&b.autoPlay());tool.$M(b.ul,{t:-d})},50);tool.removeClass(b.li[b.old],b.cur);tool.addClass(b.li[b.c],b.cur);for(var e=0,f=b.text.length;e<
f;e++){var g=b.text[e];tool.$M(tool.$$("li",g)[b.old],{d:"none"});tool.$M(tool.$$("li",g)[b.c],{d:"block"})}b.old=b.c}};
var lazyLoadImg={init:function(){var a=this;a.timer=null;a.imgList=tool.$$$("lazyLoadImg","img");for(var b=0,c=this.imgList.length;b<c;b++){var d=this.imgList[b];d.t=tool.getPos(d).top}this.imgList.sort(function(a,b){return a.t-b.t});a.setLoad();a.oldScroll=window.onscroll;a.oldResize=window.onresize;window.onscroll="function"==typeof a.oldScroll?function(){a.oldScroll();a.timeLoad()}:function(){a.timeLoad()};window.onresize="function"==typeof a.oldResize?function(){a.oldResize();a.timeLoad()}:function(){a.timeLoad()}},
unBind:function(){var a=this;window.onscroll="function"==typeof a.oldScroll?function(){a.oldScroll()}:null;window.onresize="function"==typeof a.oldResize?function(){a.oldResize()}:null},timeLoad:function(){lazyLoadImg.timer=setTimeout(function(){lazyLoadImg.setLoad()},100)},setLoad:function(){var a=tool.getW(),a=a.h+a.s,b=this.imgList.length;0>=b&&this.unBind();for(var c=0;c<b;c++){var d=this.imgList[c];if(d.t<=a)d.src=d.getAttribute("_src"),tool.removeClass(d,"lazyLoadImg");else{this.imgList.splice(0,
c);break}}}},voiceList={init:function(a,b){var c=this;this.box=tool.$(a);this.list=tool.$$("ul",this.box);this.box.appendChild(this.list[0].cloneNode(!0));this.c=0;this.l=this.list.length;this.h=b||476;this.autoPlay();c.outTimer=null;tool.addHandler(this.box,"mouseover",function(){clearInterval(c.outTimer);clearInterval(c.timer)});tool.addHandler(this.box,"mouseout",function(){c.outTimer=setTimeout(function(){c.autoPlay()},100)})},autoPlay:function(){var a=this;this.timer=setInterval(function(){a.c==
a.l-1&&(a.c=0,a.box.style.top="0px");a.c++;a.move()},7E3)},move:function(){function a(){b.box.style.top=Math.ceil(Tween.Quad.easeOut(f,c,d,e))+"px";f<e&&(f+=2,setTimeout(a,10))}var b=this,c=parseInt(tool.getCss(b.box).top),d=-b.h*b.c-c,e=100,f=0;a()}},Tween={Quad:{easeIn:function(a,b,c,d){return c*(a/=d)*a+b},easeOut:function(a,b,c,d){return-c*(a/=d)*(a-2)+b},easeInOut:function(a,b,c,d){return 1>(a/=d/2)?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b}}},shihuoPro={init:function(){var a=this;this.li=$("#shihuoPro li");
this.li1=this.li.eq(0);this.li2=this.li.eq(1);this.li3=this.li.eq(2);this.li4=this.li.eq(3);this.pos=[{fx:"top",p:-98},{fx:"left",p:155},{fx:"left",p:-155},{fx:"top",p:98}];this.time=4E3;this.c=0;this.li1.hover(function(){a.pos[0].p=-98;$(this).find(".mask").stop();$(this).find(".mask").animate({top:a.pos[0].p},200)},function(){$(this).find(".mask").stop();$(this).find(".mask").animate({top:0},200)});this.li4.hover(function(){a.pos[3].p=98;$(this).find(".mask").stop();$(this).find(".mask").animate({top:a.pos[3].p},
200)},function(){$(this).find(".mask").stop();$(this).find(".mask").animate({top:0},200)});this.li2.hover(function(){a.pos[1].p=155;$(this).find(".mask").stop();$(this).find(".mask").animate({left:a.pos[1].p},200)},function(){$(this).find(".mask").stop();$(this).find(".mask").animate({left:0},200)});this.li3.hover(function(){a.pos[2].p=-155;$(this).find(".mask").stop();$(this).find(".mask").animate({left:a.pos[2].p},200)},function(){$(this).find(".mask").stop();$(this).find(".mask").animate({left:0},
200)});a.li.eq(0).find(".mask").animate({top:a.pos[0].p},500);this.timer1=setInterval(function(){3>a.c?a.c++:a.c=0;a.li.each(function(b){if(a.c==b)switch(b){case 0:a.li.eq(0).find(".mask").animate({top:a.pos[0].p},500);break;case 1:a.li.eq(1).find(".mask").animate({left:a.pos[1].p},500);break;case 2:a.li.eq(2).find(".mask").animate({left:a.pos[2].p},500);break;case 3:a.li.eq(3).find(".mask").animate({top:a.pos[3].p},500)}else switch(b){case 0:a.li.eq(0).find(".mask").animate({top:0},500);break;case 1:a.li.eq(1).find(".mask").animate({left:0},
500);break;case 2:a.li.eq(2).find(".mask").animate({left:0},500);break;case 3:a.li.eq(3).find(".mask").animate({top:0},500)}})},a.time)}};
