$(document).ready(function(){addEventForTab();addEventForPageBtn();addTxtLinks(0);loadLingguangyishan(1);addEventForLingguangPage();addTrackEvent()});
function addEventForTab(a){a?$(".tab",$(a)):$(".tab");$(".tab").click(function(a){a.stopPropagation();var a=$(this).attr("data-type"),c=$(this).attr("data-canvas"),c=$(c);$(".tab").removeClass("cur");$(this).addClass("cur");switch(a){case "important":getBasketballMatches(c,"important");addTxtLinks(0);break;case "basketball":getBasketballMatches(c,"nba");addTxtLinks(1);break;case "football":getFootballMatches(c,"important"),addTxtLinks(2)}})}
function addTxtLinks(a){for(var b=$("#txtAdLinks").val(),b=b.split(";"),a=b[a].split(","),b=0;b<a.length;b++){var c=a,d=b,f=template,e=a[b],e=e.split("|");c[d]=f({title:e[0],link:e[1]})}$("#js-txtAd").html(a.join("|"))}function template(a){var b=$("#ad-template").html(),c;for(c in a)b=b.replace("{{"+c+"}}",a[c]);return b}
function addEventForSubTab(){$(".subtab").click(function(a){a.preventDefault();a.stopPropagation();var a=$(this).attr("data-type"),b=$(this).attr("data-canvas"),b=$(b);$(".subtab").removeClass("cur");$(this).addClass("cur");switch(a){case "nba":getBasketballMatches(b,"nba");break;case "cba":getBasketballMatches(b,"cba");break;case "football-important":case "football-yingchao":case "football-xijia":case "football-dejia":case "football-yijia":case "football-ouguan":a=a.split("-"),getFootballMatches(b,
a[1])}})}function getFootballMatches(a,b,c){b={type:"soccer",league:b};c&&(b.turn=c);$.ajax({url:$("#url-match").val(),data:b,contentType:"text/html; charset=utf-8",beforeSend:function(){$("#matchListContainer").html('<div class="noneScore">比赛信息加载中...</div>')},success:function(b){a.html(b);addEventForSubTab();addEventForFootballPageBtn()}})}
function getBasketballMatches(a,b,c){var d={};d.type=b;c&&(d.date=c);$.ajax({url:$("#url-match").val(),data:d,contentType:"text/html; charset=utf-8",beforeSend:function(){$("#matchListContainer").html('<div class="noneScore">比赛信息加载中...</div>')},success:function(b){a.html(b);addEventForSubTab($(a));addEventForPageBtn()}})}
function addEventForPageBtn(){$(".page").click(function(a){a.preventDefault();a.stopPropagation();var a=$(this).attr("data-type"),b=$(this).attr("data-canvas"),c=$(this).attr("data-date");getBasketballMatches($(b),a,c)})}function addEventForFootballPageBtn(){$(".commonlun").click(function(a){a.preventDefault();a.stopPropagation();var a=$(this).attr("data-canvas"),b=$(this).attr("data-league"),c=$(this).attr("data-turn");getFootballMatches($(a),b,c)})}
function loadLingguangyishan(a){$.ajax({url:$("#url-lingguang").val(),contentType:"text/html; charset=utf-8",data:{page:a},error:function(){$("#lingguang").html("加载灵光一闪失败")},success:function(a){$("#lingguang").html(a);$("#no-track").length||$("#lingguang a[data-track]").click(function(a){a.stopPropagation();commonGa($(this).data("track"))})}})}
function addEventForLingguangPage(){$("#lingguang-next").click(function(a){a.preventDefault();a.stopPropagation();var a=$("#lingguang-paging"),b=+a.attr("data-currentPage")+1;5<=b&&(b=5,$(this).hide());$("#lingguang-pre").show();a.attr("data-currentPage",b);loadLingguangyishan(b)});$("#lingguang-pre").click(function(a){a.preventDefault();a.stopPropagation();var a=$("#lingguang-paging"),b=+a.attr("data-currentPage")-1;1>=b&&(b=1,$(this).hide());$("#lingguang-next").show();a.attr("data-currentPage",
b);loadLingguangyishan(b)})}function addTrackEvent(){$("#no-track").length||($("[data-track]").click(function(a){a.stopPropagation();a=$(this).data("track");a=parseKeywords(a,$(this));commonGa(a)}),$("[data-track-block]").each(function(a,b){var c=$(b),d=c.data("track-block");$("a",c).click(function(a){a.stopPropagation();a=parseKeywords(d,$(this));commonGa(a)})}))}function parseKeywords(a,b){var c=$(b),c=$.trim(c.text().replace(" ",""));return c=a.replace("{{innerText}}",c)};
